sudo: false
language: python
cache: pip

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

env:
  matrix:
  - USE_SETUP=1 USE_COVERALLS=0
  - USE_SETUP=0 USE_COVERALLS=1

install:
  - if [[ "$USE_SETUP" == "0" ]]; then
      pip install -r requirements.txt ;
    fi
  - if [[ "$USE_COVERALLS" == "1" ]]; then
      pip install coveralls ;
    else
      pip install coverage ;
    fi

script:
  - if [[ "$USE_SETUP" == "1" ]]; then
      python setup.py test ;
    else
      coverage run --source=requests_oauthlib -m nose ;
    fi

after_success:
  - if [[ "$USE_COVERALLS" == "1" ]]; then
      coveralls ;
    fi
